### ISSUE TITLE
Reward evaluation and success evaluation don't match

### ISSUE THREAD

**Issue by ghost** [thu-coai/ConvLab-2#195]
In `Analyzer`, the task success is evaluated by evaluator
https://github.com/thu-coai/ConvLab-2/blob/a067adb84a0175f28f41cc192b6a6e31a497e654/convlab2/util/analysis_tool/analyzer.py#L145
and it use `BiSession`
https://github.com/thu-coai/ConvLab-2/blob/a067adb84a0175f28f41cc192b6a6e31a497e654/convlab2/util/analysis_tool/analyzer.py#L28

However, the reward is evaluated by user_agent in `BiSession` like this
https://github.com/thu-coai/ConvLab-2/blob/a067adb84a0175f28f41cc192b6a6e31a497e654/convlab2/dialog_agent/session.py#L129
if we use MultiWoz user simulator, the greatest positive reward is obtained when task is completed
https://github.com/thu-coai/ConvLab-2/blob/a067adb84a0175f28f41cc192b6a6e31a497e654/convlab2/policy/rule/multiwoz/policy_agenda_multiwoz.py#L142-L154

I found that task completion and task success aren't the same thing, right?
So why reward isn't evaluated by evaluator?

**Comment by zqwerty** [comment]
task completion is measured by the user simulator, which does not involve db match and ground truth system act.
task success is measured by the evaluator, which will access system act if available and consider db result.
Generally, task success rate will be lower than the task completion rate, since the system's recommendation does not always satisfy user constraints.
We use the reward from simulators, since different simulators can have different reward functions.You may also use the reward from the unique evaluator.

**Comment by ghost** [comment]
So in your implementation of MultiWOZ's agenda-based user simulator, the greatest reward is obtained when task is completed but not successful.
If I didn't make mistake, I would be wondering why this really make sense.

In my opinion, the user simulator is designed to train a policy that can make "successful dialgue", instead of "completed dialogue".

**Comment by zqwerty** [comment]
You are right. We will modify `Analyzer`

**Comment by ghost** [comment]
Thanks a lot!
